config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tests
  resources :questions
  resources :answers
  resources :results
  root 'tests#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :test
  has_many :answers, dependent: :destroy
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :test
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:format])

  end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to question_path(@answer.question_id)
    else
      render 'new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:format])
  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update(answer_params)
      redirect_to question_path(@answer.question_id)
    else
      render 'edit'
    end
  end

  def destroy
    @answer = Answer.destroy(params[:id])
    @question = Question.find(params[:format])
    redirect_to question_path(@question.id)
  end

  private

  def answer_params
    params.require(:answer).permit(:name, :correct, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
   @question = Question.new
   @test = Test.find(params[:format])
  end

  def edit
    @question = Question.find(params[:id])
    @test = Test.find(params[:format])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to test_path(@question.test_id)
    else
      render 'edit'
    end
  end

  def show
    @question  = Question.find(params[:id])
    @answers = Answer.where(question_id: @question.id)
  end

  def destroy
    @question = Question.destroy(params[:id])
    @test = Test.find(params[:format])

    redirect_to test_path(@question.test_id)
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to test_path(@question.test_id)
    else
      render 'new'
    end
  end

  private

  def question_params
    params.require(:question).permit(:name, :test_id)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def show
   @test = Test.find(params[:id])
   @results = Result.where(test_id: @test.id)
  end

  def create
    @result = Result.new(result_params)
    @test = Test.find(@result.test_id)

    if @result.save
      redirect_to result_path(@test.id)
    else
      render 'new'
    end
   end

  def destroy
    @result = Result.find(params[:id])
    @test = Test.find(params[:format])
    @result.destroy
    redirect_to result_path(@test.id)
  end

  def new
    @result = Result.new
    @test = Test.find(params[:format])
    @questions = Question.where(test_id: @test.id)
  end

  private

  def result_params
    params.require(:result).permit(:name, :surname, :group, :test_id)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.all
  end

  def new
  @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to @test
    else
      render 'new'
    end
  end

  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to tests_url
    else
      render 'edit'
    end
  end

  def destroy
    @test = Test.destroy(params[:id])
    redirect_to tests_path
  end


  def show
    @test = Test.find(params[:id])
    @questions = Question.where(test_id: @test.id)
  end

  private

  def test_params
    params.require(:test).permit(:name, :description)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/Results/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1><%= @test.name %></h1>

    <p>
      <%= @test.description %>
    </p>
  </div>
</div>

<hr/>

<h2 class="page-header">Student information</h2>

<%= form_for @result, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @result.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @result, field_name: :name %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @result.errors[:surname].any? %>">
      <%= f.label :surname, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :surname, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @result, field_name: :surname %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @result.errors[:group].any? %>">
      <%= f.label :group, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :group, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @result, field_name: :group %>
      </div>
    </div>

    <div class="col-sm-10">
      <%= f.hidden_field :test_id, :value => params[:format] %>
    </div>

    <h2 class="page-header">Questions</h2>
    <% counter = 0 %>
    <% @questions.each do |question| %>
        <% @answers = Answer.where(question_id: question.id) %>
        <% counter += 1 %>
        <h3>Question <%= counter %>: <span style="font-size: 20px; color: red"><%= question.name %></span></h3>
        <% counter_for_answers = 0 %>
        <% @answers.each do |answer| %>
            <% counter_for_answers += 1 %>
            <p style="font-size: 17px"><%= f.radio_button "#{counter}", answer.name, :checked => false %>
              <%= counter_for_answers %>)
              <i><%= answer.name %></i></p>
        <% end %>
    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Finish exam', class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/Results/show.html.erb
<ol class="breadcrumb" style="margin-top: 20px">
  <li><%= link_to 'Назад', root_path %></li>
  <li class="active"><%= @test.name %></li>
  <li class="active">Results</li>
</ol>

<div class="row">
  <div class="col-sm-12">
    <h1>
      Results for <%= @test.name %></h1>
  </div>
</div>

<hr/>

<table class="table table-striped">
  <tr>
    <th>Student</th>
    <th>Correct</th>
    <th>View report</th>
    <th>Actions</th>
  </tr>
  <% @results.each do |result| %>
      <tr>
        <td><%= result.name%> <%= result.surname%>, <%= result.group%></td>
        <td>Correct</td>
        <td>View report</td>
        <td>
          <%= link_to 'Delete', result_path(result, @test),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this report?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/answers/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Edit Answer</h1>
  </div>
</div>

<hr/>

<%= form_for @answer, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @answer.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @answer, field_name: :name %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @answer.errors[:correct].any? %>">
      <%= f.label :correct, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.select(:correct, [['Correct', true], ['Incorrect', false]])%>
        <%= render 'shared/field_errors', object: @answer, field_name: :correct %>
      </div>
    </div>

    <div class="col-sm-10">
      <%= f.hidden_field :question_id, :value => params[:format] %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/answers/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Answer</h1>
  </div>
</div>

<hr/>

<%= form_for @answer, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @answer.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @answer, field_name: :name %>
      </div>
    </div>

    <div class="col-sm-10">
      <%= f.hidden_field :question_id, :value => params[:format] %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Student testing', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Logged in as a teacher, <%= link_to current_user.name, '', class: 'navbar-link' %>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/questions/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1> Edit your question</h1>
  </div>
</div>

<hr/>

<%= form_for @question, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @question.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @question, field_name: :name %>
      </div>
    </div>

    <div class="col-sm-10">
      <%= f.hidden_field :test_id, :value => params[:format] %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Question</h1>
  </div>
</div>

<hr/>

<%= form_for @question, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @question.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @question, field_name: :name %>
      </div>
    </div>

    <div class="col-sm-10">
      <%= f.hidden_field :test_id, :value => params[:format] %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/questions/show.html.erb
<ol class="breadcrumb" style="margin-top: 20px">
  <li><%= link_to 'Назад', test_path(@question.test_id) %></li>
  <li class="active"><%= @question.name %></li>
  <li class="active">Answers</li>
</ol>

<div class="row">
  <div class="col-sm-12">
    <h1>
      <%= @question.name %> <%= link_to 'New Answer', new_answer_path(@question.id), class: 'btn btn-success' %></h1>
  </div>
</div>

<hr/>

<table class="table table-striped">
  <tr>
    <th>Answers</th>
    <th>Is correct</th>
    <th>Actions</th>
  </tr>
  <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.name %></td>
        <td>
          <div
          <% if answer.correct == true %>
          class="label label-success"
          <% else %>
          class="label label-danger"
          <% end %>
           style="font-size: 15px"
          >
            <%= answer.correct %>
          </div>
        </td>

        <td>
          <%= link_to 'Edit', edit_answer_path(answer, @question.id) %>
          <%= link_to 'Delete', answer_path(answer, @question.id),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this answer?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>